version: '3.8'

services:
  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - API_KEY=58f8aa7261e0bcfb1ab85c9b5e124a7bab8a0cc80fca9aeb8d148fcbb0f2ca55
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
